### ISSUE TITLE
benchmark testing of sails

### ISSUE THREAD

**Issue by alexjp** [artificialio/sane#125]
Hi,

I have been doing some benchmark testing in sails. At first, i did these testing, thinking about how much performance i would lose if i used rails as the backend. I was startled when i saw that i would actually gain more than twice the performance !

I did several tests of several frameworks. All the frameworks are at their "virgin" state, except when change was needed to make them "respond the same thing" : list of users.
The only difference in this is Sails, where i changed the controller responde to just 'hi'! ( no logic code or database query ), in an attempt to make sails faster.

Bellow are the links with the results of the tests done: give or take 10/20 req/s, they are mostly stable and coherent.

sails: http://pastebin.com/ystSShX0
rails-api : http://pastebin.com/YFw1vUYD
loopback: http://pastebin.com/LLPwwJTB

I tested other frameworks, compoundjs, goland api2go. compoundjs was in the 1700 req/s area. Go trashed everything, using little memory, almost no cpu.
I also tested jruby (puma server) and gave good performance ( more than 2000 req/s ) and handled well (no errors ) with stress tests ( concurrency at more than 500 p/s, sails would give alot of errors at this stage ).

All in all, next weekend i will finish my port of the sails server to rails-api ( pretty simple and fast, since i have long experience in rails ) and i guess its easy to move between sails and rails.

I am opening this issue because i am most surprised with the results of sails. I was convinced that it would be much faster than rails ( used unicorn server ).

Could someone also test ? I used loadtest : https://www.npmjs.com/package/loadtest

Thanks !

**Comment by mgenev** [comment]
Thanks for this, I'm looking at this module and will play with it right now: https://github.com/zanchin/node-http-perf

**Comment by tjwebb** [comment]
Can you post the configs for sails?

**Comment by mgenev** [comment]
yes there a repo somewhere with "prod configured" sails to play with?

**Comment by alexjp** [comment]
@tjwebb  sure, will do this as soon as i can.

@mgenev i will upload all 3 configurations: sails, rails-api and loopback.

notice though, loopback is only for reference, i dunno how to use loopback with emberjs

**Comment by alexjp** [comment]
can you guys check :
https://github.com/alexjp/lt_sails
and
https://github.com/alexjp/lt_rails-api

the running command line and scores are on the readme.md , just be sure to show it as "RAW", because formatting is wrong :(

**Comment by alexjp** [comment]
uploaded testing with loopback: https://github.com/alexjp/lt_loopback

warning.... i dunno loopback, never did a project with loopback, its just for testing.

**Comment by alexjp** [comment]
remark: 
sails was configured to just reply 'hi'.
rails-api was configured to fetch all users from sqlite3

all tests were done when project was running from ram ( /tmp on a systemd linux system , which is tmpfs: ram )

**Comment by tjwebb** [comment]
> r 30 2015 08:54:11 GMT+0100 (WEST)] INFO Target URL:http://localhost:1337/users [Mon Mar 30 2015 08:54:11 GMT+0100 (WEST)] INFO Max requests: 10000 [Mon Mar 30 2015 08:54:11 GMT+0100 (WEST)] INFO Concurrency level: 10 [Mon Mar 30 2015 08:54:11 GMT+0100 (WEST)] INFO Agent: none [Mon Mar 30 2015 08:54:11 GMT+0100 (WEST)] INFO [Mon Mar 30 2015 08:54:11 GMT+0100 (WEST)] INFO C

cannot read

**Comment by alexjp** [comment]
tjwebb should be better, moved the results to a results.txt file

**Comment by mgenev** [comment]
I tested for several hours on a macbook pro. My testing results differ quite a bit.

I test the same payload, with the same settings as the op, 10 000 requests, 10 concurrent requests and what somewhat consistently is:

Node's Raw http: 2200 rps 
Koa: ~2000 rps
Express: ~2000 rps (usually a bit less than koa)
Hapi: 1500 rps
Loopback: 1100 rps
Sails: 1100 rps
Rails out of the box with Webrics server: 222 rps

Rails in prod mode with unicorn set to 4 workers: 1400-1500 rps
Sails in prod mode with some hooks and middleware disabled: 1400-1500 rps

I ran many times and loopback, sails and rails with unicorn consistently come out very similar for me.

Something important to be said is though that this test is not that objective and informative, because you'd have to test very many different scenarios and cpu load levels and scaling etc. to have a really good grip the likes of which Paypal, Walmart, Intuit and GoDaddy have reported in their transitions to Java to Node. Groupon too reported huge gains from switching from Rails to Node. I'm pretty willing to believe that they did it a lot better than I did.

**Comment by IanVS** [comment]
This was a good discussion and I'm glad it came up and sparked a fair bit of investigation and discussion.  I think it's also useful to mention here the limitations of such benchmarking Node.js, and for that http://hueniverse.com/2014/08/20/performance-at-rest/ is a good article to read.  It seems best to close this issue, since it is not exactly a SANE issue, keeping in mind that this does not necessarily mean the conversation is over.

**Comment by alexjp** [comment]
I am glad, didn't want to downplay Sails or Sane, but instead share my experience and if possible improve things.
If i can help in any other way, please say so!

Thanks.

**Comment by Globegitter** [comment]
@alexjp I am glad you reported this - there is probably more to be done to get sails performance closer to express/koa, though you will of course always loose some as sails does much more work for you than express, etc.
