### ISSUE TITLE
Client cannot connect server

### ISSUE THREAD

**Issue by tarlepp** [artificialio/sane#142]
After I run ```sane up``` I'll get following errors from client side:

```bash
client   | Error proxying to http://127.0.0.1:1337
client   | connect ECONNREFUSED
client   | Error: connect ECONNREFUSED
client   |     at exports._errnoException (util.js:746:11)
client   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
```

Also if I go to URL ```http://localhost:1337``` there isn't anything to indicate that sails is up and running. Any ideas how to solve this?

**Comment by jamemackson** [comment]
@tarlepp I believe this may be caused by your lodash issue you reported which is likely preventing the sails server from starting properly and thus there is no server responding on port 1337.  Please install the sails-dev-hook as i describe in https://github.com/artificialio/sane/issues/141 and see if that corrects this issue.

**Comment by tarlepp** [comment]
Issue #141 solved this too, thanks for help!

**Comment by ayushm-agrawal** [comment]
Issue #141 didn't fix it for me. Help!
![capture](https://cloud.githubusercontent.com/assets/14841465/24811852/6fc1250e-1b8d-11e7-8ba3-486b7b2254b6.PNG)
![image](https://cloud.githubusercontent.com/assets/14841465/24811874/81846116-1b8d-11e7-8e66-e4e5947a28a2.png)
![image](https://cloud.githubusercontent.com/assets/14841465/24811897/949c8418-1b8d-11e7-93af-6fa950c976ef.png)
